= 服务拓扑

使用服务器部署服务的时候，各个服务之间的依赖关系通常是需要额外的工作来维护的。比如有一个MySQL数据库，在典型的运维场景，你想知道哪些应用依赖他就比较费劲，尤其是在一个变换频繁的团队中是需要一个统筹来管理的。 reploop-topology的目的就是快速发现服务拓扑，其基本假设是一台机器提供服务必须要监听服务端口，并且建立网络连接。这是典型的分布式场景下通过网络连接起来的多机器之间的交互方式。

== 拓扑

主要利用 `lsof` 与 `ps` 命令获取主机上的监听的端口与服务进程。 需要在目标机器上执行如下命令：

[source,shell script]
----
sudo lsof -i 4 -nPR;
sudo ps -ef;
----

`lsof` 命令获取机器上的所有网络连接，其中也包括了本地监听的端口信息，同时利用 `ps` 取得机器上的所有的服务进程。接着通过 `lsof` 和 `ps` 的输出结果中的相同的 *pid* 可以将网络连接归属到同一个服务进程，并且发现了进程之间的依赖关系。 接着将服务进程通过启动命令归属到同一个应用服务，这样就通过网络连接建立起此连接两端对应的服务之间的连接关系。

== 名词

IP:: IP地址，每个网卡(NIC)有一个IP地址，并且在其子网内是唯一的。
Port:: 网络端口，对于TCP协议，每个机器上是唯一的，同一时间不能被多个应用复用。有些端口是临时端口，可也就是只会出现一次的那种，处理的时候要注意。根据协议不同，有可能是TCP或者UDP协议。 TCP和UDP可以公用同一个端口，比如DNS服务可以同时绑定tcp/53和udp/53端口。 对于UDP的来说，一个端口可以同时被多个不同的应用绑定。
Process:: 服务进程, 通过服务主入口区分不同的进程。也就是启动命令与main函数的命名空间。
Server:: 机器，物理上的一台机器或者虚拟机。每台机器可以有多个网卡(NIC)，也就是多个IP。
Server Port:: 服务器端口，一个服务的基本服务形式，一个服务上监听一个服务端口。 这里用(服务器:端口)取代通常理解的(IP:PORT)的形式，来处理一台机器上多网卡的情况。
Service:: 应用服务，应用层面的服务，不考虑部署结构的应用服务。

.ER图
[graphviz,relation,svg]
----
digraph g {
    node[shape=box];
    IP[label="IP"];
    SERVER[label="Server"];
    PORT[label="Port"];
    SERVER_PORT[label="Server Port"];
    PROCESS[label="Process"];
    SERVICE[label="Service"];

    IP -> SERVER[label="1:1"];
    SERVER -> IP[label="1:n"];
    SERVER_PORT -> SERVER[label="1:1"];
    SERVER_PORT -> PROCESS[label="1:1"];
    PROCESS -> SERVER_PORT[label="1:n"];
    PROCESS -> SERVICE[label="1:1"];
    SERVICE -> PROCESS[label="1:n"];
    SERVER_PORT -> PORT[label="1:1"];

    {rank=min;IP;PORT;}
    {rank=same;SERVER;SERVER_PORT;}
}
----

通过lsof输出的网络连接IP:PORT->IP:PORT最终建立起Service之前的拓扑关系。

.服务拓扑
[graphviz,service,svg]
----
digraph sg {
    node[shape=box];
    rankdir=LR;
    UNKNOWN[label="Clound"];
    SERVICE[label="Service0"];
    SERVICE1[label="Service1"];
    SERVICE2[label="Service2"];
    SERVICE3[label="Service3"];
    SERVICE4[label="Service4"];
    UNKNOWN->SERVICE->SERVICE2->SERVICE3->SERVICE->SERVICE4->SERVICE2;
    SERVICE2->SERVICE1;
    SERVICE->SERVICE1;
}
----

== IP地址处理

在一个服务器上监听一个端口，通常有几种写法：

- *:Port, 监听所有网卡端口，也就是机器上的所有IP都可以访问这个端口。
- 0.0.0.0:Port, 监听IPv4的端口，

以及本地回环地址127.0.0.1。 这些地址都将会处理为具体的IP地址。 具体是首先会通过 `lsof` 的输出结果中汇总出有连接建立的所有本地IP地址，然后用这些IP地址来替换上面出现的特殊形式的IP地址。

== Process关系

Linux服务器上的每个Process都有两个id，分别是PID与PPID。同一时刻服务器上的所有PID是不重复的，但是已经消亡的进程PID后面是可以重复被利用的。

Linux下进程之间是一个树的关系，一个进程通过PPID指向其父进程。这点在处理 `lsof` 的输出时很重要，因为一个进程本身可以监听端口，也可以让子进程去监听端口提供服务。比如一些守护进程做的事就是其他真正的服务子进程去服务，自己则是一直监控着子进程的健康状态。 但是所有的子进程都应该看作一个服务进程来处理。

== 缺点

短连接场景 :: lsof运行的时机很重要，可能采集不到或者不全。
定时任务 :: 同样也是lsof的运行时机很重要，可能采集不到或者不全。
外部服务 :: 第三方服务识别需要提前标注。此部分针对的是机器不能登陆的情况下，获取不到具体信息的情况，都归类为外部第三方服务。
多进程与进程管理 :: 通过Linux系统进程管理与监控工具启动的服务，真正服务的是子进程，这个影响服务的识别。

== 应用场景

以下是一些典型的应用场景：

发现空闲机器:: 机器上没有服务进程的话，可以认为机器是空闲的。或者可以辅以其他信息识别空闲机器。
理解服务拓扑:: 理解服务之间的调用依赖关系。在抄抄代码的开发模式下，可能会无意引入不必要的服务。
识别意外服务:: 一般应用服务非常好理解，但是这些服务所依赖的辅助服务，经常被忽略。比如读写文件系统，日志监控服务等。

== 结论

在微服务体系下，调用链是必备的。通过他也是可以画出服务拓扑关系的。也就不需要这么麻烦了。

== 参考

* https://lwn.net/Articles/542629/